NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

CytronBabitchBundle_API:
    resource: "@CytronBabitchBundle/Resources/config/routing.yml"
    prefix:   /v1
